INSERT INTO tier_items (tier_list_id, ranking, placed, photo) 
VALUES
(1, 'S', TRUE, 'https://i.imgur.com/VaweL8b.png'),
(2, 'S', TRUE, 'https://i.imgur.com/VaweL8b.png'),
(1, 'A', TRUE, 'https://i.imgur.com/Q1ctILq.png'),
(1, 'A', TRUE, 'https://i.imgur.com/Q1ctILq.png'),
(1, 'B', TRUE, 'https://i.imgur.com/6fyQ9YF.png'),
(2, 'B', TRUE, 'https://i.imgur.com/6fyQ9YF.png'),
(1, 'C', TRUE, 'https://i.imgur.com/N5ZdQzO.png'),
(1, 'D', TRUE, 'https://i.imgur.com/nFPH5Pf.png'),
(1, 'F', TRUE, 'https://i.imgur.com/Q1ctILq.png'),
(1, 'F', TRUE, 'https://i.imgur.com/1EmhucE.png'),
(2, 'F', TRUE, 'https://i.imgur.com/1EmhucE.png'),
(1, NULL, FALSE, 'https://i.imgur.com/ItgTcsI.png'),

(3, 'F', TRUE, 'https://assets.bonappetit.com/photos/5c62e4a3e81bbf522a9579ce/5:4/w_2815,h_2252,c_limit/milk-bread.jpg'),
(3, 'A', TRUE, 'https://thewoksoflife.com/wp-content/uploads/2021/04/sourdough-bread-recipe-22.jpg'),
(3, 'D', TRUE, 'https://www.vegankitchenmagick.com/wp-content/uploads/2018/04/img_8602.jpg'),
(3, 'S', TRUE, 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/focaccia-f599171.jpg'),
(3, 'C', TRUE, 'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Gluten--and-Dairy-Free-Cinnamon-Raisin-Bread_EXPS_FT19_227132_F_0723_1.jpg'),
(3, 'B', TRUE, 'https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/recipe_legacy/8-3-large.jpg?itok=fRNQugY8'),
(3, 'B', TRUE, 'https://media.self.com/photos/5daa23395c250800081afa68/4:3/w_2560%2Cc_limit/sprouted-whole-grain-bread.jpg'),
(3, 'B', TRUE, 'https://static.toiimg.com/thumb/76531928.cms?width=1200&height=900'),
(3, 'S', TRUE, 'https://static01.nyt.com/images/2018/12/11/dining/as-garlic-bread/as-garlic-bread-articleLarge.jpg'),
(3, 'A', TRUE, 'https://i1.wp.com/smittenkitchen.com/wp-content/uploads//2020/03/sk-ultimate-banana-bread.jpg?fit=1200%2C800&ssl=1');